namespace SmartPackingSolution.Geometry;

using SmartPackingSolution.Models;

/// <summary>
/// Maintains the set of candidate anchor positions where the next package may be placed.
/// </summary>
/// <remarks>
/// <para>
/// This is the extreme-point scheme of Crainic, Perboli and Tadei. When a package is
/// placed, each of its far corners is projected back along the negative X, Y and Z axes
/// until it meets an existing surface. The resulting anchors hug the geometry already in
/// the container, so packages nest into the gaps between neighbours instead of only
/// stacking at the three corners of the box just placed.
/// </para>
/// <para>
/// Positions are snapped to a grid before being stored. Anchors are produced by repeated
/// addition of package dimensions, so two anchors describing the same physical corner can
/// differ in their last bits; without snapping, exact-equality de-duplication silently
/// fails and the candidate set grows without bound.
/// </para>
/// </remarks>
public sealed class ExtremePointSet
{
    private readonly double _grid;
    private readonly double _tolerance;
    private readonly HashSet<Position> _points = [];
    private IReadOnlyList<Position>? _ordered;

    /// <summary>
    /// Initializes a new set containing only the container origin.
    /// </summary>
    /// <param name="grid">The snap step applied to every stored position.</param>
    /// <param name="tolerance">The slack used in geometric comparisons.</param>
    public ExtremePointSet(double grid, double tolerance)
    {
        _grid = grid;
        _tolerance = tolerance;
        _points.Add(Position.Origin);
    }

    /// <summary>
    /// Gets the number of candidate positions currently held.
    /// </summary>
    public int Count => _points.Count;

    /// <summary>
    /// Returns the current candidate positions ordered lowest, then deepest, then leftmost.
    /// </summary>
    /// <returns>The ordered anchor positions.</returns>
    /// <remarks>
    /// The ordering is cached until the set changes. Sorting it afresh for every package
    /// made the search cost grow with the anchor count on each of the n placements, which
    /// dominated the run once a few hundred anchors had accumulated.
    /// </remarks>
    public IReadOnlyList<Position> Ordered() =>
        _ordered ??= [.. _points.OrderBy(p => p.Z).ThenBy(p => p.X).ThenBy(p => p.Y)];

    /// <summary>
    /// Removes a position that has been consumed by a placement.
    /// </summary>
    /// <param name="position">The position to remove.</param>
    public void Remove(Position position)
    {
        if (_points.Remove(position.Quantize(_grid)))
        {
            _ordered = null;
        }
    }

    /// <summary>
    /// Adds the anchors generated by a newly placed box.
    /// </summary>
    /// <param name="placed">The box that was just placed.</param>
    /// <param name="existing">All boxes already in the container, including <paramref name="placed"/>.</param>
    /// <param name="bounds">The container's dimensions.</param>
    public void AddFrom(in AxisAlignedBox placed, IReadOnlyList<AxisAlignedBox> existing, Dimensions bounds)
    {
        ArgumentNullException.ThrowIfNull(existing);
        ArgumentNullException.ThrowIfNull(bounds);

        // The three corners abutting the new box's far faces, then each projected back
        // onto whatever surface lies behind it on the other two axes.
        Span<(double X, double Y, double Z)> seeds =
        [
            (placed.MaxX, placed.MinY, placed.MinZ),
            (placed.MinX, placed.MaxY, placed.MinZ),
            (placed.MinX, placed.MinY, placed.MaxZ),
            (placed.MaxX, placed.MaxY, placed.MinZ),
            (placed.MaxX, placed.MinY, placed.MaxZ),
            (placed.MinX, placed.MaxY, placed.MaxZ)
        ];

        foreach (var seed in seeds)
        {
            if (seed.X > bounds.Length + _tolerance ||
                seed.Y > bounds.Width + _tolerance ||
                seed.Z > bounds.Height + _tolerance)
            {
                continue;
            }

            Add(new Position(seed.X, seed.Y, seed.Z));
            Add(new Position(seed.X, ProjectY(seed, existing), seed.Z));
            Add(new Position(ProjectX(seed, existing), seed.Y, seed.Z));
            Add(new Position(seed.X, seed.Y, ProjectZ(seed, existing)));
        }
    }

    /// <summary>
    /// Drops anchors once the set exceeds a cap, keeping the most promising ones.
    /// </summary>
    /// <param name="max">The maximum number of anchors to retain.</param>
    public void Prune(int max)
    {
        if (_points.Count <= max)
        {
            return;
        }

        var keep = _points
            .OrderBy(p => p.Z)
            .ThenBy(p => p.X + p.Y)
            .Take(max)
            .ToHashSet();

        _points.IntersectWith(keep);
        _ordered = null;
    }

    private void Add(Position position)
    {
        if (position.X < -_tolerance || position.Y < -_tolerance || position.Z < -_tolerance)
        {
            return;
        }

        if (_points.Add(position.Quantize(_grid)))
        {
            _ordered = null;
        }
    }

    /// <summary>Slides a point back along -X until it meets the nearest surface or the wall.</summary>
    private double ProjectX((double X, double Y, double Z) seed, IReadOnlyList<AxisAlignedBox> existing)
    {
        var best = 0.0;
        foreach (var box in existing)
        {
            if (box.MaxX <= seed.X + _tolerance &&
                seed.Y >= box.MinY - _tolerance && seed.Y < box.MaxY - _tolerance &&
                seed.Z >= box.MinZ - _tolerance && seed.Z < box.MaxZ - _tolerance &&
                box.MaxX > best)
            {
                best = box.MaxX;
            }
        }

        return best;
    }

    /// <summary>Slides a point back along -Y until it meets the nearest surface or the wall.</summary>
    private double ProjectY((double X, double Y, double Z) seed, IReadOnlyList<AxisAlignedBox> existing)
    {
        var best = 0.0;
        foreach (var box in existing)
        {
            if (box.MaxY <= seed.Y + _tolerance &&
                seed.X >= box.MinX - _tolerance && seed.X < box.MaxX - _tolerance &&
                seed.Z >= box.MinZ - _tolerance && seed.Z < box.MaxZ - _tolerance &&
                box.MaxY > best)
            {
                best = box.MaxY;
            }
        }

        return best;
    }

    /// <summary>Drops a point along -Z until it lands on the nearest surface or the floor.</summary>
    private double ProjectZ((double X, double Y, double Z) seed, IReadOnlyList<AxisAlignedBox> existing)
    {
        var best = 0.0;
        foreach (var box in existing)
        {
            if (box.MaxZ <= seed.Z + _tolerance &&
                seed.X >= box.MinX - _tolerance && seed.X < box.MaxX - _tolerance &&
                seed.Y >= box.MinY - _tolerance && seed.Y < box.MaxY - _tolerance &&
                box.MaxZ > best)
            {
                best = box.MaxZ;
            }
        }

        return best;
    }
}
